ALTER TABLE rewards
ADD COLUMN IF NOT EXISTS price NUMERIC(10,2) DEFAULT 0 NOT NULL,
ADD COLUMN IF NOT EXISTS normal_point_cost INT DEFAULT 0 NOT NULL,
ADD COLUMN IF NOT EXISTS valid_from TIMESTAMPTZ;
